<script setup lang="ts">
import MessageComponent from './components/Message.vue'
import type { ChatMessage, Data, Conversation } from './lib/types'
import { ChatCompletionRequestMessageRoleEnum } from './lib/types'
import { v4 as uuid } from 'uuid'
import { useListStore } from './stores/conversationList'
import { useChatRoomStore } from './stores/chatroom'
import { useStatusStore } from './stores/status'
import { faker } from '@faker-js/faker'
import { onMounted, ref } from 'vue'
import { getResponse } from './lib/ChatGPTMock'

onMounted(() => {
  useListStore().loadConversationList()
  useChatRoomStore().$reset()
})

const listStore = useListStore()
const chatRoomStore = useChatRoomStore()
const statusStore = useStatusStore()

const switchConversation = (id: string) => {
  chatRoomStore.clickloadMessageObject(id)
}

const inputText = ref('')
// const isLoading = ref(false)

const sendMessage = async (text: string) => {
  if (text.trim() === '' || statusStore.isLoading) return
  if (chatRoomStore.currentMessageList.length == 0) {
    let results = clickNewConversation()
    // Create a new conversation
    excuteCreateConversation(results.conversation, results.data)
  }
  let id = uuid()
  chatRoomStore.addMessage({
    id,
    text,
    role: ChatCompletionRequestMessageRoleEnum.User,
    parentMessageId: chatRoomStore.data!.current_node,
    children: []
  })
  inputText.value = ''

  // request ChatGPT Mock API
  statusStore.isLoading = true
  let response = await getResponse(text)
  chatRoomStore.addMessage({
    ...response,
    parentMessageId: id
  })

  statusStore.isLoading = false
}

const keypressSendMessage = (event: KeyboardEvent) => {
  if (event.shiftKey) return
  sendMessage(inputText.value)
}

const clickNewConversation = () => {
  let id = uuid()
  // let title = 'New chat'
  let title = faker.company.name()
  let create_time = new Date().getTime()

  // Root node
  let root: ChatMessage = {
    id,
    role: ChatCompletionRequestMessageRoleEnum.System,
    text: '',
    children: []
  }

  //
  let newData: Data = {
    title,
    create_time,
    mapping: {
      [id]: root
    },
    current_node: id
  }

  let newConversation: Conversation = {
    id,
    title,
    create_time
  }

  chatRoomStore.$reset()

  // Before creating a new conversation, the user needs to send a message, otherwise, it will not be created.
  return {
    data: newData,
    conversation: newConversation
  }
}

// Save a new conversation
const excuteCreateConversation = (conversation: Conversation, data: Data) => {
  listStore.addConversation(conversation)
  chatRoomStore.createConversation(data)
}

// Click "Regernate" button, it will use send
const regenerateResonpse = async () => {
  statusStore.isLoading = true

  /*
  The "new message" generated by ChatGPT can be connected to the last node of the user's message, 
  which can be obtained by subtracting 2 from the length of the current message list in the chat room store 
  (i.e., chatRoomStore.currentMessageList.length - 2).
  */
  let lastUserNode =
    chatRoomStore.currentMessageList[chatRoomStore.currentMessageList.length - 2]

  // request for ChatGPT Mock API
  let response = await getResponse('')
  chatRoomStore.addMessage({
    ...response,
    parentMessageId: lastUserNode.id
  })
  statusStore.isLoading = false
}

const clickDeleteConversation = (index: number, id: string) => {
  chatRoomStore.clickDeleteConversation(id)
  listStore.deleteConversationFromList(index)
  chatRoomStore.$reset()
}

const clickClearAllConversation = () => {
  if (confirm('Are you sure delete all conversation?')) {
    listStore.List.forEach((item) => chatRoomStore.clickDeleteConversation(item.id))
    listStore.deleteConversationList()
  }
}
</script>

<template>
  <div class="bg-base-100 w-full h-screen relative">
    <div class="overflow-hidden flex flex-1 flex-col h-full bg-black-100">
      <!-- Ignore Nav Bar -->

      <div class="flex flex-1 min-h-screen border">
        <!-- This section displays the list of conversations on the left side of the screen START -->
        <div class="w-1/4 bg-base-200 flex flex-col">
          <button class="btn btn-outline m-2" @click="clickNewConversation">+</button>
          <ul class="menu bg-base-200">
            <!-- Conversation List START -->
            <li
              v-for="(list, index) in listStore.List"
              :key="list.id"
              @click="switchConversation(list.id)"
            >
              <a
                class="flex justify-between"
                :class="{ active: chatRoomStore.conversationId == list.id }"
              >
                <div class="w-full">{{ list.title }}</div>
                <!-- ref: https://stackoverflow.com/questions/48798216/prevent-event-bubbling-in-vue -->
                <span
                  v-if="chatRoomStore.conversationId == list.id"
                  class="btn btn-xs btn-outline"
                  @click.stop="clickDeleteConversation(index, list.id)"
                  >del</span
                >
              </a>
            </li>
            <!-- Conversation List END -->
            <!-- Just Divider -->
            <li></li>
          </ul>
          <button
            v-if="listStore.List.length > 0"
            class="btn btn-outline m-2"
            @click="clickClearAllConversation"
          >
            Clear All
          </button>
        </div>
        <!-- This section displays the list of conversations on the left side of the screen END -->

        <!-- This section is for the chat room and will be located on the right side of the page START -->
        <div class="w-3/4 bg-base-100 flex flex-col justify-between">
          <div
            v-if="chatRoomStore.currentMessageList.length == 0"
            class="flex h-screen justify-center items-center"
          >
            <h1 class="font-semibold text-gray-600 text-4xl mr-2">ChatGPT</h1>
            <span class="text-xs rounded-lg bg-yellow-200 text-yellow-800 py-1 px-1.5 uppercase"
              >Structure</span
            >
          </div>
          <div v-else class="h-full bg-base-100 overflow-y-auto relative">
            <MessageComponent
              v-for="(message, index) in chatRoomStore.currentMessageList"
              :index="index"
              :message="message"
              :key="message.id"
            />
            <!-- https://tailwind-elements.com/docs/standard/components/spinners/ -->
            <!-- Loading START -->
            <div v-if="statusStore.isLoading" class="w-full p-10 bg-base-100">
              <div class="flex items-center justify-center">
                <div
                  class="inline-block h-8 w-8 animate-spin rounded-full border-4 border-solid border-current border-r-transparent align-[-0.125em] motion-reduce:animate-[spin_1.5s_linear_infinite]"
                  role="status"
                >
                  <span
                    class="!absolute !-m-px !h-px !w-px !overflow-hidden !whitespace-nowrap !border-0 !p-0 ![clip:rect(0,0,0,0)]"
                  ></span>
                </div>
              </div>
            </div>
            <!-- Loading END -->
          </div>
          <div class="flex flex-col items-center bg-neutral px-1 py-2">
            <!-- Regenerate Response START -->
            <button
              v-if="chatRoomStore.currentMessageList.length > 0"
              class="btn btn-primary w-1/2"
              :class="{ 'btn-disabled': statusStore.isLoading }"
              @click="regenerateResonpse"
            >
              regenerate
            </button>
            <!-- Regenerate Response END -->

            <!--  Message Typing START -->
            <div class="flex justify-center w-full md:w-2/3 mb-0 md:my-6">
              <input
                v-model="inputText"
                type="text"
                placeholder="Type here"
                class="input w-full input-ghost w-full max-w-xs"
                @keypress.enter.prevent="keypressSendMessage"
              />
              <button
                class="btn"
                :class="{ 'btn-disabled': statusStore.isLoading }"
                @click="sendMessage(inputText)"
              >
                Send
              </button>
              <!-- Message Typing END -->
            </div>
          </div>
        </div>
        <!-- This section is for the chat room and will be located on the right side of the page END -->
      </div>
    </div>
  </div>
</template>
